apiVersion: v1
kind: Pod
metadata:
  name: model-exporter
  namespace: kubeflow
spec:
  restartPolicy: Never
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: stock-data
  containers:
    - name: model-exporter
      image: busybox
      command: ["sleep", "300"]
      volumeMounts:
        - name: data
          mountPath: /data
