apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-data
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
